### ISSUE TITLE
Troubles compiling and using the software

### ISSUE THREAD

**Issue by AxelKrypton** [Irubataru/openqcd-to-qdp#1]
I wanted to give this very useful tool a try, but I had some troubles both compiling and using the main executable.

About compilation I could not compile using neither `v2.0` nor `v1.6` of openQCD. In both cases I got the following error.

```
CXX obj/qdp_archive.o
CXX obj/openqcd_utilities.o
In file included from library/openqcd_utilities.cpp:8:
include/openqcd_utilities.hpp: In function ‘void fastsum::OpenQCD::Initialise()’:
include/openqcd_utilities.hpp:29:51: error: too few arguments to function ‘bc_parms_t set_bc_parms(int, double, double, double, double, double*, double*, double*)’
   29 |   set_bc_parms(3, 0., 0., 0., 0., nullptr, nullptr);
      |                                                   ^
In file included from include/openqcd_utilities.hpp:17,
                 from library/openqcd_utilities.cpp:8:
/home/sciarra/Documents/Programs/openQCD-1.6/include/flags.h:252:19: note: declared here
  252 | extern bc_parms_t set_bc_parms(int type,
      |                   ^~~~~~~~~~~~
make: *** [Makefile:56: obj/openqcd_utilities.o] Error 1
```

Using `v1.4` works, tough, and I could get my executable.

However, I failed running it with a 12x72x72x72 configuration, which was produced with openQCD-FASTSUM. In particular, this results in
```
[klotho:1631094] *** Process received signal ***
[klotho:1631094] Signal: Segmentation fault (11)
[klotho:1631094] Signal code: Address not mapped (1)
[klotho:1631094] Failing at address: 0x55d16c739000
[klotho:1631094] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x153c0)[0x7fd6bee163c0]
[klotho:1631094] [ 1] ./bin/openqcd-to-qdp(+0x39edd)[0x55d1fad20edd]
[klotho:1631094] [ 2] ./bin/openqcd-to-qdp(+0x3afaf)[0x55d1fad21faf]
[klotho:1631094] [ 3] ./bin/openqcd-to-qdp(+0x218d3)[0x55d1fad088d3]
[klotho:1631094] [ 4] ./bin/openqcd-to-qdp(+0x1a81b)[0x55d1fad0181b]
[klotho:1631094] [ 5] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7fd6bec360b3]
[klotho:1631094] [ 6] ./bin/openqcd-to-qdp(+0x1b63e)[0x55d1fad0263e]
[klotho:1631094] *** End of error message ***
Segmentation fault
```
and I am wondering whether and what I might be doing wrong. Is it actually possible to convert configurations produced with openQCD-FASTSUM? I also tried in the beginning to use openQCD-FASTSUM instead of openQCD, but this did not work and I was probably too optimistic trying so... :sweat_smile: 

I cloned and compiled qdpxx according to your issue [here](https://github.com/usqcd-software/qdpxx/issues/8), which was definitely useful form me... :expressionless: 

**Side remark.** It was for me not immediate to understand that I had to edit the `openQCD-1.4/include/global.h` file to make the program _serial_ and match the lattice size. Adding a more explicit note in your README might be useful.

**Comment by Irubataru** [comment]
Hi Alessandro,

It's been a while since I looked at this and I should probably archive it. This project evolved into a different one that is on the fastsum gitlab: [oniconverter](https://gitlab.com/fastsum/oniconverter). In that program you do not need to precompile the lattice sizes as it uses the library version of openQCD to allow dynamic lattice sizes. Would you mind giving that a try before I try to find out what is wrong with this one?

In that repo I wanted to try out bazel as a build system, however, if you checkout the branch labeled [nonrec-make](https://gitlab.com/fastsum/oniconverter/-/tree/nonrec-make) then there's a version with make compatibility. I should probably merge that branch and write some documentation one day, it's another project that is basically done but I never found the time to do the final touches to.

**Comment by AxelKrypton** [comment]
:cool: I will give it a try and report here. If the functionality there is the same and it is handier, even better!
